### ISSUE TITLE
Images aren't displayed

### ISSUE THREAD

**Issue by aadcg** [alexmurray/emacs-snap#5] opened 2019-09-14 17:01 UTC
Hi,

I can't seem to be able to open any image file on Emacs (imagemagick mode). Any ideas on how to fix this?

I'm on Ubuntu 19.04.

**Comment by alexmurray** [comment] 2019-09-15 00:18
What version of the snap are you using?

**Comment by alexmurray** [comment] 2019-09-15 06:31
Ok I just tried it on a Ubuntu 19.04 VM and I believe I can reproduce this - when loading an image all that is shown is a white square, not the actual image, and interestingly no obvious errors are displayed.

```
sudo snap install --classic --beta emacs
emacs /snap/emacs/current/usr/share/emacs/26.3/etc/images/icons/hicolor/128x128/apps/emacs.png
```

![emacs_no_images_ubuntu_1904](https://user-images.githubusercontent.com/56540/64917695-70a68080-d7c5-11e9-8270-f3ec04d4d8c9.png)

**Comment by alexmurray** [comment] 2019-09-15 06:39
Interestingly the `snapshot` build of emacs from the `edge` channel (which is current emacs git - 27.0.50) works better for images, likely because upstream has deprecated the imagemagick backend (https://emba.gnu.org/emacs/emacs/commit/d2dea70415ca7ec390a2de11b224ab4cbb2c6b55) and so this uses native code for handling images now. Which gives a strong hint this is likely an issue due to emacs being compiled as a snap with imagemagick on Ubuntu 18.04 but then running on Ubuntu 19.04 with a different imagemagick library or similar.

**Comment by aadcg** [comment] 2019-09-15 15:36
Thank you for looking into it. This white square is exactly what I also get.
So, I guess the solution would be to run the latest Emacs from the `edge` channel.

**Comment by alexmurray** [comment] 2019-09-16 15:01
@aadcg I am hoping to come up with a solution for the stable channel as well - will keep this bug report updated with progress.

**Comment by alexmurray** [comment] 2019-10-16 06:21
This should now be fixed - a new build is now available from the `beta` channel - if you could please install this as follows:

    sudo snap refresh emacs --beta

and then confirm that this is working correctly, I will promote this release to the `stable` channel and this issue can be closed.

**Comment by alexmurray** [comment] 2019-10-16 11:00
Closing this as fixed and promoting this to the `stable` channel - please reopen if you find it is not working

**Closed by alexmurray** 2019-10-16 11:00 UTC
