### ISSUE TITLE
GLIBC_2.33 errors when installing on Ubuntu 21.04

### ISSUE THREAD

**Issue by maacl** [alexmurray/emacs-snap#29] opened 2021-04-23 11:07 UTC
I get the bellow errors when starting emacs after install on Ubuntu 21.04:

```
/snap/emacs/1090/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/../../../../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/snap/emacs/1090/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/../../../../lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
```

**Comment by alexmurray** [comment] 2021-04-23 13:45
Thanks for reporting this issue, I think I fixed something quite similar to this for the edge channel recently so I'll take a look at this when I'm next in front of the computer, that may not be until Tuesday next week but will let you know as soon as I can.

**Comment by maacl** [comment] 2021-04-23 14:29
OK, so maybe edge would work?

**Comment by maacl** [comment] 2021-04-23 14:34
For info I get same error when installing:

sudo snap install emacs --channel=latest/edge --classic

**Comment by alexmurray** [comment] 2021-04-28 06:46
Hmm I can't reproduce this myself on my local Ubuntu 21.04 machine but I will try later in a freshly installed VM to see if I can reproduce it further.

**Comment by maacl** [comment] 2021-04-28 06:57
OK, let me know if I can provide further info. This was tested on a clean Hyper V Ubuntu 21.04 vm.

**Comment by alexmurray** [comment] 2021-04-29 01:48
Ok so I can reproduce this and I see these messages printed on startup but it does not appear to have a material impact - we already set `GIO_MODULE_DIR` to try and avoid this sort of thing (ie a mismatch between the host gio modules and the ones shipped inside the emacs snap) so I am not sure there is much else to be done here. Can you confirm whether emacs is functioning correctly even when you see these messages?

**Comment by maacl** [comment] 2021-04-29 06:04
I can confirm that emacs appears to work correctly despite these messages.

**Comment by alexmurray** [comment] 2021-04-29 07:06
Ok let's leave this issue open for now since I think I would still like to try and find a way to avoid this as it's definitely a bit scary even if it doesn't affect the functionality of emacs.

**Comment by maacl** [comment] 2021-04-29 07:15
OK, let me know if you want me to verify any fixes.

**Comment by alexmurray** [comment] 2021-04-30 07:09
This should be fixed by 482b944 on master and ecce32c on snapshot (aka edge) - so once the snap rebuilds in a couple hours then I hope this will be resolved.

**Comment by maacl** [comment] 2021-04-30 07:24
Cool I will verify later today.

**Comment by maacl** [comment] 2021-04-30 12:54
It is still giving the same error as of 20 mins. ago.

**Comment by alexmurray** [comment] 2021-04-30 13:08
Yeah I was hoping the new builds would be done by now but they are taking longer than expected - hopefully will be done in another hour or two perhaps

**Comment by alexmurray** [comment] 2021-05-03 09:28
@maacl builds are now done - can you confirm if this is fixed for you via the emacs 27.2 build on the beta channel or the 28.0.50 build on edge?

**Comment by maacl** [comment] 2021-05-03 12:23
I can confirm that this now runs cleanly on a fresh Hyper V Ubuntu 20.04 VM. Thanks.

**Comment by alexmurray** [comment] 2021-05-03 12:41
No worries, thanks for reporting the issue in the first place.

**Closed by alexmurray** 2021-05-03 12:41 UTC

**Comment by EvanMath** [comment] 2021-06-04 13:11
Hello there,
After upgrading Ubuntu from 20.04 to 21.04 I am getting the above message and in some cases, Emacs just freeze on a white screen. I have also removed and installed again Emacs but it remains the same. Any help?

**Comment by alexmurray** [comment] 2021-06-07 05:44
@EvanMath apologies, I had forgotten to promote the fixed builds from the beta to the stable channel - this is now fixed on the stable channel as well.

**Comment by gjm** [comment] 2023-05-25 13:49
I've just encountered this error with emacs beta channel on Ubuntu 23.04.
