### ISSUE TITLE
Linker error on vanilla Emacs 28.1 (Ubuntu 21.10)

### ISSUE THREAD

**Issue by FilConscious** [alexmurray/emacs-snap#35] opened 2022-04-05 16:23 UTC
After updating Emacs to version 28.1 in Ubuntu 21.10, I get the same error as in https://github.com/alexmurray/emacs-snap/issues/22. However, in my case, that happens with a vanilla Emacs installation (no doom-emacs).

--- **Emacs outputs** ---

- Warnings:

Warning (comp): libgccjit.so: error: error invoking gcc driver Disable showing Disable logging
Warning (comp): /snap/emacs/current/usr/share/emacs/28.1/lisp/url/url-vars.el.gz: Error: Internal native compiler error failed to compile Disable showing Disable logging

- Async-native-compile-log:

Compiling /snap/emacs/current/usr/share/emacs/28.1/lisp/url/url-vars.el.gz...
uncompressing url-vars.el.gz...
uncompressing url-vars.el.gz...done
ld: cannot find crtbeginS.o: No such file or directory
ld: cannot find -lgcc
ld: cannot find -lgcc_s
libgccjit.so: error: error invoking gcc driver
/snap/emacs/current/usr/share/emacs/28.1/lisp/url/url-vars.el.gz: Error: Internal native compiler error failed to compile
Compilation finished.

--- End of Emacs outputs ---

A couple of additional notes:

- before the update I had already an installation of GCC (version Ubuntu 11.2.0-7ubuntu2) in the system because it was needed by the package `emacsql-sqlite`;
- after getting the error I thought `libgccjit` was missing in my system so I installed it from the Ubuntu repos (specifically `libgccjit-11-dev`) but it did not help;
- replacing the directories in the Emacs variable `native-comp-driver-options` with the system directories where GCC is located did not help either.

**Comment by ddovod** [comment] 2022-04-05 18:21
Hello. I'm facing the same issue, ubuntu 20.04. Btw is there a way to temporarily rollback the version to the previous one?

**Comment by alexmurray** [comment] 2022-04-05 21:23
Thanks for reporting this issue, clearly supporting native-comp across multiple distros as a classic snap is more difficult than I expected. I'll roll the snap back to 27.2 for the stable channel until I can get this sorted out.

**Comment by ldav1s** [comment] 2022-04-05 21:36
Back in business with the 27.2 snap.  Thanks for the quick response!

**Comment by FilConscious** [comment] 2022-04-05 21:53
Thanks indeed for the quick/temporary fix! 

@ddovod, to roll back you can now simply execute `snap refresh emacs` into the terminal and everything should be working as before.

**Comment by alexmurray** [comment] 2022-04-05 23:32
So I just tried reproducing this in a fresh Ubuntu 21.10 VM and it all appears to work fine - I installed emacs from the beta channel to get 28.1 and then ran it and there are no errors - then I did `M-x package-refresh-contents` and then `M-x package-install` `ace-window` and I don't see any errors in the `*Async-native-compile-log*` buffer (see [async-native-compile-log.txt](https://github.com/alexmurray/emacs-snap/files/8422438/async-native-compile-log.txt)).

How are you invoking emacs?

**Comment by alexmurray** [comment] 2022-04-06 04:26
Since I am unable to reproduce this (I tried on both Ubuntu 21.10 and 20.04 - on fresh VMs) I am tempted to set 28.1 back to stable - so any help you could give in trying to help me reproduce this would be great @FilConscious @ddovod @ldav1s

**Comment by mousetrappling** [comment] 2022-04-06 05:27
I had exactly the same error as the original report, tho I didn't know to check the async-native-compile-log.  Ubuntu 20.04.  I run emacs using the icon shortcut on my Gnome Applications Menu (I think that's the official name for the bar down the side).  Is it possible the problem happens on systems that have upgraded emacs rather than a fresh install?

(Don't think I can be much help tracking this down I'm afraid, I've used linux a long time but I'm not really a power user (and I'm a relatively new emacs user).)

**Comment by alexmurray** [comment] 2022-04-06 05:56
Ah thanks - ok so I can reproduce this by first:

1. Install emacs from the stable channel
2. Install a package (say ace-window) via `M-x package-install` then selecting `ace-window`
3. Shutdown emacs
4. Refresh emacs from the beta channel to install emacs 28.1
5. Restart emacs
6. Notice the error occurs and then looking in `*Async-native-compile-log*`:
```
Compiling /snap/emacs/current/usr/share/emacs/28.1/lisp/url/url-vars.el.gz...
uncompressing url-vars.el.gz...
uncompressing url-vars.el.gz...done
ld: cannot find crti.o: No such file or directory
ld: cannot find crtbeginS.o: No such file or directory
ld: cannot find -lgcc
ld: cannot find -lgcc_s
ld: cannot find -lc
ld: cannot find -lgcc
ld: cannot find -lgcc_s
ld: cannot find crtendS.o: No such file or directory
ld: cannot find crtn.o: No such file or directory
libgccjit.so: error: error invoking gcc driver
/snap/emacs/current/usr/share/emacs/28.1/lisp/url/url-vars.el.gz: Error: Intern\
al native compiler error failed to compile
Compilation finished.
```

Will see what I can do.

**Comment by root42** [comment] 2022-04-06 07:17
The gccjit problem can be fixed by installing libgccjit-9 with apt. That's how I got Emacs 28 working at least.

**Comment by alexmurray** [comment] 2022-04-06 07:29
No you shouldn't need to install anything to get it working - the emacs snap should ship everything it requires and make sure it configures itself to use those pieces and not have to rely on users installing other packages - I have a potential fix in progress, will let you know when it is available.

**Comment by alexmurray** [comment] 2022-04-06 10:43
With any luck should be fixed by [6308794](https://github.com/alexmurray/emacs-snap/commit/630879459853da7962c5ba3d9da06f9d55b5054a) - this should be in the beta channel in the next few hours.

**Comment by alexmurray** [comment] 2022-04-06 11:55
Nope turns out that is not sufficient... am trying another approach.

**Comment by alexmurray** [comment] 2022-04-06 13:16
Ok from my own testing this looks to be fixed now and snaps with the fix are available in the beta channel.

Can someone else please try using the snap from the beta channel and see if it works for them? 

```
snap refresh emacs --beta
```

Thanks.

**Comment by root42** [comment] 2022-04-06 13:44
I tried it, having removed the libgccjit libs beforehand, which I installed manually. Seems to work fine! 
Ubuntu 20.04.4 LTS.

**Comment by alexmurray** [comment] 2022-04-06 13:49
Thanks, I've just promoted it to stable.

**Closed** 2022-04-06 13:49 UTC
